RUN_NAME: 'bloodMNIST_usl'

SKIP_SAVE: False
RECOMPUTE_ALL: True
RECOMPUTE_NUM_DEP: True

DATASET:
  NAME: 'bloodmnist'
  TRANSFORM_NAME: 'medMNIST'

MODEL:
  ARCH: 'resnet18'
  PRETRAIN_PATH: 'pretrained/spice_BloodMNIST.pth.tar'

USL:
  NUM_SELECTED_SAMPLES: 16
  KNN_K: 100
  SEEDS: [1, 2, 3, 4, 5]
